/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.commandpattern.App;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootContextLoader;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationContext;

import static org.junit.jupiter.api.Assertions.assertTrue;

@SpringBootTest(classes = App.class)
class AppTest {

    @Autowired
    private ApplicationContext applicationContext;
    @Test void appHasAGreeting() {
        assertTrue(applicationContext.getBeanDefinitionCount() > 0);
    }
}
